
import streamlit as st

st.set_page_config(page_title="QuLab: Key Risk Indicator (KRIs) Framework Simulator", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab: Key Risk Indicator (KRIs) Framework Simulator")
st.divider()
st.markdown("""
In this lab, we will explore Key Risk Indicators (KRIs) and their application in operational risk management. This application allows you to simulate KRI data, set thresholds, and analyze the aggregated risk status across different business units. You can also explore the descriptions of standard KRI data fields.

**Key Features:**
- **KRI Configuration**: Select predefined KRIs and set custom Amber and Red alert thresholds.
- **Synthetic Data Generation**: Simulate time-series data for selected KRIs across multiple business locations, including underlying operational metrics.
- **Interactive Dashboards**: Visualize KRI trends over time, highlighting threshold breaches, and examine relationships between compounded KRIs.
- **Aggregated KRI View**: Provides a consolidated view of KRI statuses (Green, Amber, Red) across business units, using an aggregated comparison.
- **KRI Data Fields Exploration**: An interactive table displaying descriptions of standard KRI data fields.
""")

from application_pages.page1 import run_page1
run_page1()


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
